permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: fusky
  email: choggle2011@gmail.com
  link: http://fusky.iperson.cn
  weibo: http://weibo.com/fusky0512
  github: http://github.com/fusky

# 站点信息
title: fusky的博客
description: fusky的博客
url: http://fusky.iperson.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://blog.iperson.cn/usr/uploads/2014/11/3254891614.jpg
favicon: 

# google analytics 设置
ga:
  id: UA-54767140-1
  url: fusky.iperson.cn

# disqus 设置
disqus:
  shortname: fusky

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
